# Generated by Django 3.2.4 on 2021-06-06 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_kwargs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kwargs',
            field=models.JSONField(),
        ),
    ]
