name: Notify CI

env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker compose build 
      run: docker-compose build
    - name: start services
      run: docker-compose up -d
    - name: check running conainers
      run: docker ps -a
    - name: Run Test Cases
      run: docker-compose exec -T web_app coverage run manage.py test -v 2
    - name: Generate coverage xml
      run: docker-compose exec -T web_app coverage xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true